---
title: "p8105_hw2_yj2581"
author: "YucongJiang"
date: "2019-10-2"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
```

## Problem 1



```{r trash_wheel}
mr_trash_wheel <- read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
                             sheet = "Mr. Trash Wheel", 
                             range = "A2:N408") %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(sports_balls = as.integer(round(sports_balls)))

precipitation_2017 <- read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
                                 sheet = "2017 Precipitation",
                                 skip = 1) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2017)

precipitation_2018 <- read_excel("data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
                                 sheet = "2018 Precipitation",
                                 skip = 1) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2018)

precipitation_combine <- full_join(precipitation_2017, precipitation_2018) %>%
  mutate(month = as.character(month.name[month]))
```

#### Describe the data

```{r fivethirtyeight}
pols_month <- read_csv("data/pols-month.csv") %>%
  separate(mon, c("year", "month", "day"), "-", convert = TRUE) %>%
  mutate(month = as.character(month.name[month])) %>%
  mutate(president = if_else(prez_gop == 1, "gop", "dem")) %>%
  select(-day, -prez_gop, -prez_dem)

snp <- read_csv("data/snp.csv") %>%
  separate(date, c("month", "day", "year"), "/", convert = TRUE) %>%
  arrange(year, month) %>%
  mutate(month = as.character(month.name[month])) %>%
  select(year, month, close)

unemployment <- read_csv("data/unemployment.csv") %>%
  rename(
    year = Year,
    January = Jan,
    February = Feb,
    March = Mar,
    April = Apr,
    June = Jun,
    July = Jul,
    August = Aug,
    September = Sep,
    October = Oct,
    November = Nov,
    December = Dec) %>%
  pivot_longer(
    January:December,
    names_to = "month",
    values_to = "unemployment_proportion") %>%
  drop_na(unemployment_proportion)
  
merge_table <- full_join(pols_month, snp, by = c("year", "month")) %>%
  full_join(unemployment, by = c("year", "month"))

```

#### Describe the data

```{r popular_baby_names}
popular_baby_names <- read.csv("data/Popular_Baby_Names.csv") %>%
  janitor::clean_names() %>%
  mutate(
    ethnicity = replace(ethnicity, ethnicity == "ASIAN AND PACI", "ASIAN AND PACIFIC ISLANDER"),
    ethnicity = replace(ethnicity, ethnicity == "BLACK NON HISP", "BLACK NON HISPANIC"),
    ethnicity = replace(ethnicity, ethnicity == "WHITE NON HISP", "WHITE NON HISPANIC"),
    ethnicity = as.factor(as.character(ethnicity)),
    child_s_first_name = str_to_title(child_s_first_name)
  ) %>%
  distinct()
```

```{r table_data}
olivia_popularity <- filter(popular_baby_names, child_s_first_name == "Olivia" & gender == "FEMALE") %>%
  select(ethnicity, year_of_birth, rank) %>%
  rename(Ethnicity = ethnicity) %>%
  arrange(year_of_birth) %>%
  pivot_wider(
    names_from = "year_of_birth",
    values_from = "rank"
  )

most_popular_boyname <- filter(popular_baby_names, rank == 1 & gender == "MALE") %>%
  select(ethnicity, year_of_birth, child_s_first_name) %>%
  rename(Ethnicity = ethnicity) %>%
  arrange(year_of_birth) %>%
  pivot_wider(
    names_from = "year_of_birth",
    values_from = "child_s_first_name"
  )

knitr::kable(olivia_popularity)
knitr::kable(most_popular_boyname)
```

```{r show_plot}
count_vs_rank <- filter(popular_baby_names, gender == "MALE" & ethnicity == "WHITE NON HISPANIC" & year_of_birth == 2016) %>%
  select(count, rank)

ggplot(count_vs_rank, aes(x = rank, y = count)) + 
  geom_point() +
  labs(
    title = "Count of Name in Male White Non-hispanic Children Born in 2016",
    x = "The Rank in Popularity",
    y = "The Count of Name",
    caption = "Data from NYC Open data"
  )
```


